server:
  port: 1211

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/lbook?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      uri: mongodb://localhost:27017/ebook
  mail:
    host: smtp.qq.com
    username: xanwidtf@foxmail.com
    password: lkutgwnfwoglhghj
    properties.mail.smtp:
      auth: true
      starttls:
        enable: true
        required: true

mybatis:
  mapper-locations: classpath:/mybatis/mapping/*Mapper.xml